services:
  - type: web
    name: Uni-Chat
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true

